unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
	# Configure appWordpress
	config.vm.define "appWordpress" do |appWordpress|
		appWordpress.vm.box = "ubuntu/bionic64"
		appWordpress.vm.network "forwarded_port", guest: 80, host: 8081
		appWordpress.vm.provision :docker
		appWordpress.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
	end
	# Configure appGolang server
	config.vm.define "appGolang" do |appGolang|
                appGolang.vm.box = "ubuntu/bionic64"
                appGolang.vm.network "forwarded_port", guest: 8080, host: 8082
		appGolang.vm.provision "docker" do |dock|
			dock.build_image "/vagrant/", args: "-t golang:Final"
		end
		appGolang.vm.provision :shell do |shell|
			shell.inline = "docker run --publish 8080:8080 -t golang:Final &"
		end
	end
end
